#https://github.com/facebook/create-react-app/issues/11879
services:
  app:
    image: todo-frontend-dev
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
      - WDS_SOCKET_PORT=$REACT_LOCAL_PORT
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    container_name: todo-frontend-dev # This will name the container hello-front-dev