###
# @name user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "m.r@gmail.com",
    "name": "Matthew Ruse"
}

###
# @name user2
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "mr@gmail.com",
    "name": "Matthew Ruse"
}

###
GET http://localhost:3001/api/users

###
PUT http://localhost:3001/api/users/{{user.response.body.$.username}}
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{
    "username": "mynewusername"
}

###
# @name login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "m.r@gmail.com",
    "password": "secret"
}

###
# @name login2
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mr@gmail.com",
    "password": "secret"
}

###
GET http://localhost:3001/api/blogs
Authorization: Bearer {{login.response.body.$.token}}

###
GET http://localhost:3001/api/blogs?search=Newest
Authorization: Bearer {{login.response.body.$.token}}

###
GET http://localhost:3001/api/blogs?search=Jones
Authorization: Bearer {{login.response.body.$.token}}

###
# @name blog
POST http://localhost:3001/api/blogs
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{
    "author": "Bill Jones",
    "url": "http://billyjones.com/blogpost",
    "title": "My newest blog"
}

###
# @name blog2
POST http://localhost:3001/api/blogs
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{
    "author": "Bill Jones",
    "url": "http://billyjones.com/blogpost2",
    "title": "My newest blog 2"
}


###
PUT http://localhost:3001/api/blogs/{{blog.response.body.$.id}}
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{
    "likes": 5
}

###
DELETE  http://localhost:3001/api/blogs/{{blog.response.body.$.id}}
Authorization: Bearer {{login2.response.body.$.token}}