@baseUrl = http://localhost:3001/api

POST {{baseUrl}}/persons
content-type: application/json

{
    "name": "Bilbo Baggins", 
    "number": "040-34434"
}
###
// Should fail due to number missing
POST {{baseUrl}}/persons
content-type: application/json

{
    "name": "Billy"
}
###
// Should fail due to name
POST {{baseUrl}}/persons
content-type: application/json

{
    "number": "040-34434"
}
###
// Should fail due to name and number missing
POST {{baseUrl}}/persons
content-type: application/json

{
    
}
###
POST {{baseUrl}}/persons
content-type: application/json

{
    "name": "Ada Lovelace", 
    "number": "040-34434"
}
###
// Should fail due to too short name
POST {{baseUrl}}/persons
content-type: application/json

{
    "name": "Ad", 
    "number": "040-34434"
}
###
// Should fail due invalid number
POST {{baseUrl}}/persons
content-type: application/json

{
    "name": "Ada jones", 
    "number": "10-22-334455"
}
