@baseUrl = http://localhost:3001/api

POST {{baseUrl}}/persons
content-type: application/json

{
    "name": "Bilbo Baggins", 
    "number": "040-34434"
}
###
POST {{baseUrl}}/persons
content-type: application/json

{
    "name": "Billy"
}
###
POST {{baseUrl}}/persons
content-type: application/json

{
    "number": "040-34434"
}
###
POST {{baseUrl}}/persons
content-type: application/json

{
    
}
###
POST {{baseUrl}}/persons
content-type: application/json

{
    "name": "Ada Lovelace", 
    "number": "040-34434"
}
###
POST {{baseUrl}}/persons
content-type: application/json

{
    "name": "Ad", 
    "number": "040-34434"
}