@baseUrl = http://localhost:3001/api

# @name createPerson

POST {{baseUrl}}/persons
content-type: application/json

{
    "name": "Bilbo Baggins", 
    "number": "040-34434"
}
###

# @name updatePerson
@personId = {{createPerson.response.body.$.id}}
PUT {{baseUrl}}/persons/{{personId}}
content-type: application/json

{
    "name": "Bilbo Baggins", 
    "number": "040-3443465634343"
}

###
// Should fail due to too short name
@personId = {{createPerson.response.body.$.id}}
PUT {{baseUrl}}/persons/{{personId}}
content-type: application/json

{
    "name": "Bi", 
    "number": "040-3443465634343"
}