version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    hostname: mongodb
  redis:
    image: redis
    ports:
      - 5478:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes: 
      - redis_data:/data
    hostname: redis
  server:
    image: todo-backend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app
    ports:
      - 3210:3000
    environment: # can hardcode these since only the dev server
    - MONGO_URL=mongodb://the_username:the_password@mongodb:27017/the_database
    - REDIS_URL=redis://redis:6379
    container_name: todo-backend-dev
volumes:
  mongo_data:
  redis_data: